### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by garrett** [cthiel/cardboard#10]
There's no favicon. It needs one.

**Comment by cthiel** [comment]
How about a sticky note icon? http://www.iconfinder.com/search/?q=sticky

**Comment by bear454** [comment]
The tomboy icon?  It's already got an easy license

**Comment by cthiel** [comment]
You were thinking of http://projects.gnome.org/tomboy/images/tomboy-128.png? @garrett, views?

**Comment by cthiel** [comment]
Fixed in commit f82db75c2273f434fe60

**Comment by garrett** [comment]
No, we'd want to make use of a 16x16 icon for the favicon.

We _could_ cobble together multiple sizes in the Gimp.

I've taken the liberty to extract all the tomboy icons and toss them up on a dropbox public folder:
http://dl.dropbox.com/u/116444/tomboy/index.html

**Comment by garrett** [comment]
Okay, dropbox is sloooooow right now. Here's an alternate:
http://linuxart.com/temp/tomboy-icons/

**Comment by cthiel** [comment]
http://linuxart.com/temp/tomboy-icons/hicolor_actions_22x22_filter-note-unfiled.png would be kind of funny to use as an icon :)

**Comment by garrett** [comment]
That's not a 16x16 icon though! (:

**Comment by garrett** [comment]
...and before you ask: no, you cannot just simply scale it in the Gimp. (;

**Comment by cthiel** [comment]
http://linuxart.com/temp/tomboy-icons/hicolor_apps_16x16_tomboy.png is probably the best bet then!

**Comment by garrett** [comment]
Yup. I think so, unless you want the one w/ a star! (:

**Comment by garrett** [comment]
We could rename to StarredBoard (;

**Comment by garrett** [comment]
Oh, also I'm on G+ if you want to video chat (or just audio chat if you're without a camera)

**Comment by cthiel** [comment]
Let's go for the one without the star! I don't want to do yet another rename :(

**Comment by garrett** [comment]
It looks like it's working for me.

**Comment by cthiel** [comment]
Did you actually change the icon? Or is this still the icon @bear454 put in? Maybe it's identical?

**Comment by garrett** [comment]
I didn't change it. It's a 16x16 Tomboy icon, so I consider that good enough for now. We may add multiple sizes in the future.

**Comment by cthiel** [comment]
Great! We should at least add icons for iOS, so it displays nicely on the home screen :)

**Comment by garrett** [comment]
Okay. I think we can consider that a related, but different bug. (:

..or I can just add it to the iPadification bug.
