### ISSUE TITLE
Design step missing

### ISSUE THREAD

**Issue by garrett** [cthiel/cardboard#12]
There's no design step in Kaban. 

Where is it? Should it be there instead of Analysis? ...or how does this work? (:

**Comment by cthiel** [comment]
That's up the user? Just remove the Analysis from the Statuses and add Design? We could also just change db/seed.rb to include whatever we find useful.

**Comment by garrett** [comment]
Yes, I know the user can change it. We should change the default. (:

**Comment by cthiel** [comment]
Fixed by commit fd7e1dbcb43ffd30b879.

**Comment by garrett** [comment]
Awesome! Thanks!

**Comment by garrett** [comment]
Wait. Is it at the end? It should be at the beginning. (...or perhaps when I update it, it just stuck it at the end?)

**Comment by cthiel** [comment]
Yep, I think so! Just go ahead and delete db/development.db and try again.

**Comment by garrett** [comment]
Perhaps design should go after product mgt and before development ready? I guess right after analysis?

**Comment by cthiel** [comment]
With the latests seeds.rb we would end up with:

```
ProductMgmt | Design | Development | Test | Release
```

Do you think we also need Analysis, and if so, at which stage? Before or after Design?

**Comment by garrett** [comment]
Do we need ProductMgmt? Should it be "Incoming" or something? We could either overload an "Incoming" concept with Analysis too, or squeeze it in the middle. If we have fewer columns, I think it would help us visualize things better.

```
Incoming | Design | Development | Test | Release
```

So, in this setup, Incoming would be items that are coming from Product Management and elsewhere, and during that stage they are discussed (and analyzed). They may get dropped right then, or they may proceed further.

This is the general order of things (from left to right), although some items _could possibly_ bounce between Design and Development or Development and Test a bit.

Design isn't necessarily UI design, either. Sometimes it's the design of code APIs, etc. Of course, UI is still a big chunk of design work for us. (;

**Comment by cthiel** [comment]
I think we should stay with what we have right now in the seeds, which is:

```
ProductMgmt Ready | ProductMgmt | Design Ready | Design | Development Ready | Development | Test Ready | Test | Release Ready | Release
```

If the user chooses not to run "rake db:seed", he will be able to decide what he wants his Kanban setup to look like.
