### ISSUE TITLE
Support importing stories from CSV

### ISSUE THREAD

**Issue by cthiel** [cthiel/cardboard#15]
We should add support for importing new stories from CSV

**Comment by bear454** [comment]
I'm going to work on nailing down the UI simplicity I've already committed to ;)

But I suppose its a decent option for getting some bulk data in.

**Comment by cthiel** [comment]
It doesn't have to be CSV -- maybe just as simple as adding a textfile and treat each line as story?

**Comment by bear454** [comment]
This is a subset of issue 27.
