### ISSUE TITLE
Adding references to stories

### ISSUE THREAD

**Issue by cthiel** [cthiel/cardboard#18]
It would be nice to be able to have one or many references (e.g. links to bugzilla or etherpad) attached to a story and link them from the Wall.

**Comment by cthiel** [comment]
@garrett and @bear454, do you guys think we still need this with the latests markdown changes?

**Comment by bear454** [comment]
IMO, we need to keep it as generic and simple as possible.  URLs via markdown solves this without any further complexity.

**Comment by cthiel** [comment]
That makes sense. However, we should make the markdown editing easier. Think WYSIWYG?

**Comment by garrett** [comment]
Are we supporting vanilla Markdown or a flavor, like GitHub's extended version? I guess whatever's in a Ruby Gem? Or are we using Markdown.js too? (:

**Comment by bear454** [comment]
Not relying on ruby at all... just rendering it in js using showdown.js

**Comment by garrett** [comment]
Awesome :+1:
