### ISSUE TITLE
Add name tags to stories

### ISSUE THREAD

**Issue by cthiel** [cthiel/cardboard#2]
@dmajda suggested to add name tags to stories, so that you can see who is involved with a story.

**Comment by garrett** [comment]
Good idea

**Comment by cthiel** [comment]
I'll take care of the of backend. Can you do the styling?

**Comment by garrett** [comment]
Sure!

**Comment by cthiel** [comment]
OK, the code is in master now. stories.json has it as tag_list. It just needs to get added to the board. I'll leave that up to you :)

**Comment by garrett** [comment]
Okay, nice.

I noticed that I had to do a rake db:migrate when things didn't show up as expected.

**Comment by cthiel** [comment]
Ah, sorry, I forgot to mention that. Also you had to run "bundle" again, right?

**Comment by garrett** [comment]
Yes, I did. I forgot to mention that too. (:

**Comment by cthiel** [comment]
Fix in commit f03f897ca5d7fe359aaf
