### ISSUE TITLE
Adding new stories inline

### ISSUE THREAD

**Issue by cthiel** [cthiel/cardboard#21]
It would be cool if it was possible to add new stories via double-clicking in statuses colums, just like we do with editing them.

What do you think, @garrett?

**Comment by garrett** [comment]
I think it would be nice. 

I was actually thinking about this earlier today, and was thinking about a button on the page.

Do you think that double-clicking on the empty space would be obvious, and wouldn't be a misclick? If double-clicking on the page creates a new popup, we had better respect on which column the item was double-clicked on.

New and edit are almost the same thing. Are they similar in the Ruby code?

We should start to refactor the CoffeeScript a bit. I think we could benefit from a more generic way of doing dialogs, for instance. (It's not bad as-is, but I could see a lot of the code being repeated if we don't abstract it _now_. Plus, it's always nice to make things a little tidier.)

**Comment by cthiel** [comment]
New and edit are very simliar in the Ruby code as well. You should have to call to /stories/new and if we go for double-clicking into the page, just make sure to preselect the right option in the dropdown (by id of the status column). The select input has the id "story_status_id". The value of each option is almost identical to the id of the status ul's (just replace('status','') to get the id :)) [We should actually fix that...]

**Comment by cthiel** [comment]
And yes, I think double-clicking into the page is kind of obvious. In addition to that we could also add a link or descriptive text below? Something like "to create or edit stories double-click into the status columns".

**Comment by garrett** [comment]
Feature added in commit f32dadd840c5dfbe5bc0!
