### ISSUE TITLE
Make ordering persist

### ISSUE THREAD

**Issue by cthiel** [cthiel/cardboard#24]
Let's make sure that dragging works more correct.

**Comment by bear454** [comment]
I'm thinking acts_as_list on the columns/piles/decks...

**Comment by cthiel** [comment]
Sounds like an option!

**Comment by cthiel** [comment]
@bear454, do you want to take care of also making card ordering persistant? It would be very useful, I think!

**Comment by cthiel** [comment]
I prepared for this in commit 9f821aacf84372255bc65dd3e9eb373d3ff7dacd

@garrett, please see the comment I added to the commit.

**Comment by cthiel** [comment]
Let's fix this correctly :)

**Comment by prasoonsharma** [comment]
When will this be implemented? Waiting eagerly :)

**Comment by cthiel** [comment]
This is now implemented.
