### ISSUE TITLE
Port to HAML

### ISSUE THREAD

**Issue by garrett** [cthiel/cardboard#3]
HAML is nicer, Should we port?

html2haml should do most of the erb migration.

**Comment by cthiel** [comment]
Go!

**Comment by garrett** [comment]
I'm not the Ruby guy... (:

I tried and it didn't load. Perhaps HAML needs to be enabled somehow?

**Comment by cthiel** [comment]
OK, will enable it right away :)

**Comment by garrett** [comment]
Okay, I've programatically ported all the ERB to HAML in the haml-port remote branch. We can see if it works and fix whatever broke (if anything).

**Comment by cthiel** [comment]
OK, things are fixed in the haml-port branch. Feel free to merge to master.

**Comment by cthiel** [comment]
It's merged into master now.

**Comment by garrett** [comment]
I was fixing merge commit issues... and then they disappeared and I was really confused. Now I know why! (:

Glad it's done. (;
