### ISSUE TITLE
Rename Models

### ISSUE THREAD

**Issue by cthiel** [cthiel/cardboard#31]
We should rename stories to cards (in the backend) and maybe project to board.

**Comment by cthiel** [comment]
Not sure if Statuses should stay the same or be called column?

**Comment by bear454** [comment]
Story => Card
Status => Pile/Set
Project => Board

**Comment by cthiel** [comment]
Status => Deck?

**Comment by cthiel** [comment]
Or Batch?

**Comment by bear454** [comment]
I like Deck, since their cards, but that's just me ;)

**Comment by cthiel** [comment]
Pushed.

**Comment by bear454** [comment]
GAH

We're both working on the same thing!

**Comment by cthiel** [comment]
Arrg, sorry :( I thought this was assigned to me. It all in master now.
