### ISSUE TITLE
WYSIWYG editing for Markdown?

### ISSUE THREAD

**Issue by cthiel** [cthiel/cardboard#32]
How about WYSIWYG editing for Markdown a la http://markitup.jaysalvat.com/home/?

**Comment by bear454** [comment]
Meh ;)  I'm not going to implement one... they all look yucky.  I'd rather just show people a few basic markdown concepts, and link to the rest (like we do on studio)... its pretty natural.

**Comment by garrett** [comment]
Yes, Markdown! I'm a fan. :+1:
