### ISSUE TITLE
Update Heroku demo more frequently

### ISSUE THREAD

**Issue by garrett** [cthiel/cardboard#39]
With our crazy fast-paced development, we should update http://card-board.herokuapp.com/ more frequently. (:

**Comment by cthiel** [comment]
Just did that :)

**Comment by cthiel** [comment]
I can also add you as collaborator on heroku, so you guys can push to there as well. Do you have accounts @ heroku?

**Comment by garrett** [comment]
I just signed up w/ my gmail address.

**Comment by cthiel** [comment]
OK, I added both of you as collaborator. Heroku should have sent you an email.

See http://devcenter.heroku.com/articles/sharing and http://devcenter.heroku.com/articles/collab for further details. You'll also need run `sudo gem install heroku`, to get going... If you need further assistance, let me know.
