### ISSUE TITLE
Switch to jQuery UI sortables

### ISSUE THREAD

**Issue by garrett** [cthiel/cardboard#4]
I think this draggable library we're using is quite a bit buggy. We'll either need to fix it up ourselves or port to jQuery UI's dragglables, unless there's a newer version available.

What do you think?

**Comment by cthiel** [comment]
Sure, it shouldn't be a big deal, I guess? From just looking at http://jqueryui.com/demos/draggable/ it seems to offer the events we need to get the database updated. Want to go for it?

**Comment by garrett** [comment]
Yeah, I may. I was holding off, but it probably won't be hard to do at all. It will most likely provide a much nicer experience, so it should be worth it.

**Comment by garrett** [comment]
I decided sortables (not dragables & dropables together) would be the right fit for us. I now have it working and am getting ready to commit soon.

**Comment by cthiel** [comment]
Awesome!

**Comment by garrett** [comment]
Done! Merged! Try it out! It fixes a few bugs and provides direct feedback where the item will be dropped.

**Comment by cthiel** [comment]
Sweet! Works great for me!

**Comment by garrett** [comment]
:+1: Awesome!

git + github is really a great way to collaborate, isn't it? (:

**Comment by cthiel** [comment]
It really is! :sparkles: :sparkles: :sparkles:
