### ISSUE TITLE
Starting a card with a number breaks markdown

### ISSUE THREAD

**Issue by cthiel** [cthiel/cardboard#42]
If I put something like

"20. try this out"

into a card, it will be displayed as

"1. try this out"

and also indented. We should fix this :)

**Comment by garrett** [comment]
It's not a bug, that's how markdown does numbered lists.
1. one
2. one
3. three

^ I used 1. 1. 3. for the beginning parts.

If you want a number, try this:

20: try this out

**Comment by cthiel** [comment]
Well, "20: try this out" works -- however, this still feels kind of broken :) I know of a cardboard that has like 140 cards on it, each of them starts with "somenumber(dot) title", which all looks like "1. title" in the latests version.

**Comment by garrett** [comment]
Oh, is that one of the _important_ carboards?

Perhaps the solution is to disable markdown for the first line and run it on the rest?

**Comment by cthiel** [comment]
That's what I was suggesting :) Always make the first line bold and run the rest through markdown?

**Comment by garrett** [comment]
Yeah, I think that could work. The only issue I can think of is that the first line will be an orphan and the next line will have a &lt;p&gt;. At least, I'm pretty sure that's what would happen. I suppose we can prepend the first line into the markdown block (or we'd have to play w/ strings).

I'll fiddle with it.

**Comment by garrett** [comment]
I split out the titles so that they're outside of markdown (and the complete title is bold, instead of just the first line).

Done in commits 4c864e136c4c37ea3a93f1be003b8012826dd37f and 9346d350cef453d014483cf6e565a14e5474f7e5 (a bugfix for newlines in markdown).
