### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by garrett** [cthiel/cardboard#5]
We've deviated so much from the previous versions of simplekanban we may want to consider renaming the project (or at least augment the name). Perhaps not-quite-as-simple-kanban? (:

We could also try to offer our work back upstream too.

**Comment by cthiel** [comment]
+1! Do you have a naming suggestion? I'll think about...

**Comment by garrett** [comment]
It's kind of silly, but here's a name that might work: _"Kandoit", pronounced "can do it", borrowing the "kan" from "kanban" and helping you to keep track whatever it is you're trying to get done._

Or perhaps Kantrackit? Or just Kantrack? Although if it's kantrack, it looks like "can't rack".

**Comment by garrett** [comment]
James Mason said it's just cards on a board... "cardboard" (:

Of course, it would be impossible to Google, unless we misspelled it on purpose, like kardboard (but that looks KDE-related).

**Comment by cthiel** [comment]
"cardboard" sounds good! I like it :)

**Comment by garrett** [comment]
:+1:

**Comment by garrett** [comment]
So are we all in agreement? 

Should we go ahead and switch? 

Should we fork it into a new repo and push to that and update the README here to point to that? (If we don't, then the URL will completely break... but does that matter yet?)

**Comment by cthiel** [comment]
Just rename should be fine I guess? It's not been publicized much so far, right?

**Comment by cthiel** [comment]
Also we would be able to keep the Issues around.

**Comment by garrett** [comment]
Ah, good point. Yeah, let's just rename. Simpler.

**Comment by cthiel** [comment]
Done! Thanks for the naming suggestions @garrett and @bear454.

**Comment by garrett** [comment]
You might want to de-kanban-ify the description, as it can be used for more things than just kanban.

Of course you might want to still mention it, but also mention that it can be used for card sorting, and tracking anything.

This will be especially more true once we implement more of a dynamic UI for groups.

**Comment by cthiel** [comment]
Done.
