### ISSUE TITLE
Double-click inline editing

### ISSUE THREAD

**Issue by garrett** [cthiel/cardboard#9]
It would be nice to edit each story inline.

**Comment by garrett** [comment]
As kind of a hack, we could even load the edit page and only display part of it inline via jQuery. I think it might actually work well enough, really... and we'd only have the code in one place. It would keep things simple.

**Comment by cthiel** [comment]
Either inline or just redirect to the edit url for now?

**Comment by garrett** [comment]
It can just pull the page. jQuery can fetch a page and only display part of it (you specify fetching the page with a hash and it will return just the contents of that ID). Then, just display it in a popup and dismiss it at the same time as an ajax post.

**Comment by cthiel** [comment]
Just added stories/1/edit.js that returns just the form, which could be shown inside a jquery ui modal dialog.

**Comment by cthiel** [comment]
This is just a simple hack, you can make it much nicer, I guess!

**Comment by garrett** [comment]
:sparkles: Done and _done!_ :sparkles:

Be sure to check out all the goodness I've added. I think it's quite slick now.
